const mydata = [
    {
        "id": 1,
        "tag": "Komplek Makam Sunan Sendang",
        "title": "Wisata Sunan Sendang",
        "des": "Raden Noer Rahmad ingin memiliki masjid sendiri di Desa Sendangduwur. Beliau kemudian mendapat kabar kalau seorang janda di Mantingan menjual masjidnya. Raden Noer Rahmad memutuskan pergi ke Mantingan dengan niat hendak membeli masjid tersebut. Namun, Mbok Rondo Mantingan mengatakan kalau Raden Noer Rahmad boleh mengambil masjid itu secara cuma-cuma dengan syarat beliau harus mampu memboyongnya sendirian dari Mantingan ke Sendangduwur. Syarat tersebut dirasa berat oleh Raden Noer Rahmad, sehingga beliau pulang dan bertapa di bukit Sedayu. Dari pertapaannya itu, Raden Noer Rahmad mendapat petunjuk dari Allah agar menyanggupi syarat Mbok Rondo Mantingan. Akhirnya Raden Noer Rahmad Kembali ke Mantingan untuk meminta masjid tersebut. Atas kuasa Allah, masjid tersebut dapat dibawa terbang oleh Raden Noer Rahmad dari Mantingan ke Sendangduwur.",
        "des-Full" : "Sunan Sendang atau Mbah Raden Noer Rahmad adalah putra Abdul Kohar bin Malik bin Sultan Abdul Yazid asal Baghdad. Lahir pada 1320 M dan wafat 1585 M. Raden Noer Rahmad mendapat gelar Sunan Sendang dari Sunan Drajat setelah berhasil menerima tantangannya. Dikisahkan Sunan Drajat memberi tantangan kepada Raden Noer Rahmad untuk mengambil buah siwalan dari pohonnya. Kala itu, Sunan Drajat mengambilnya dengan cara mengguncangkan batang pohon, sehingga semua buah, baik yang sudah matang atau belum matang, jatuh. Namun, Raden Noer Rahmad memiliki cara yang lebih halus yaitu dengan mengelus batang pohon, sehingga pohon tersebut menunduk dan dapat diambil buahnya yang sudah matang. Sunan Drajat takjub melihat cara Raden Noer Rahmad yang dinilai lebih bijaksana karena buah yang belum matang bisa tetap berada di pohon. Atas kemampuan tersebut, Sunan Drajat memutuskan memberi gelar Sunan Sendang untuk Raden Noer Rahmad. Setelah mendapat gelar Sunan Sendang, Raden Noer Rahmad ingin memiliki masjid sendiri di Desa Sendangduwur. Beliau kemudian mendapat kabar kalau seorang janda di Mantingan menjual masjidnya. Raden Noer Rahmad memutuskan pergi ke Mantingan dengan niat hendak membeli masjid tersebut. Namun, Mbok Rondo Mantingan mengatakan kalau Raden Noer Rahmad boleh mengambil masjid itu secara cuma-cuma dengan syarat beliau harus mampu memboyongnya sendirian dari Mantingan ke Sendangduwur. Syarat tersebut dirasa berat oleh Raden Noer Rahmad, sehingga beliau pulang dan bertapa di bukit Sedayu. Dari pertapaannya itu, Raden Noer Rahmad mendapat petunjuk dari Allah agar menyanggupi syarat Mbok Rondo Mantingan. Akhirnya Raden Noer Rahmad Kembali ke Mantingan untuk meminta masjid tersebut. Atas kuasa Allah, masjid tersebut dapat dibawa terbang oleh Raden Noer Rahmad dari Mantingan ke Sendangduwur. Awalnya Raden Noer Rahmad hendak meletakkan masjid tersebut di puncak Bukit Gendheng yang berada di Desa Sendangagung. Tapi karena masyarakat di sekitar Bukit Gendheng belum banyak, maka masjid tersebut dibawa ke puncak Bukit Amintuno di Desa Sendangduwur yang kini dikenal sebagai Masjid Raden Noer Rahmad.",
        "image1": "https://i.pinimg.com/originals/88/8d/ce/888dce2f7c9547b295ef3e3bfb9b6e70.jpg",
        "image2": "https://i.pinimg.com/originals/15/d2/a4/15d2a4ab23b38d839e4a55b934a41e17.jpg",
        "image3": "https://i.pinimg.com/originals/43/d3/41/43d3415441a1b0fb44f36417ff47ff0c.jpg",
        "image4": "https://i.pinimg.com/originals/08/e3/48/08e3481797b0a7ba7428f87f6117e873.jpg",
    },
    {
        "id": 2,
        "tag": "Paguyuban Batik Sinande",
        "title": "Wisata Edukasi Batik",
        "des" : "Program ini tidak hanya sekadar perjalanan biasa, melainkan sebuah petualangan yang akan membawa kita pada pengetahuan mendalam tentang seni dan budaya yang kaya dari Indonesia. Tak hanya itu, kita juga akan mendapatkan kesempatan langka untuk belajar langsung dari para ahli membatik. Melalui demonstrasi live, mereka akan menunjukkan teknik-teknik kuno yang digunakan dalam pembuatan batik tradisional. Ini adalah momen yang luar biasa, di mana kita dapat menyaksikan keahlian dan ketelitian yang diperlukan untuk menciptakan karya seni membatik yang memukau.",
        "des-Full": "Program ini tidak hanya sekadar perjalanan biasa, melainkan sebuah petualangan yang akan membawa kita pada pengetahuan mendalam tentang seni dan budaya yang kaya dari Indonesia. Tak hanya itu, kita juga akan mendapatkan kesempatan langka untuk belajar langsung dari para ahli membatik. Melalui demonstrasi live, mereka akan menunjukkan teknik-teknik kuno yang digunakan dalam pembuatan batik tradisional. Ini adalah momen yang luar biasa, di mana kita dapat menyaksikan keahlian dan ketelitian yang diperlukan untuk menciptakan karya seni membatik yang memukau. Namun, puncak dari pengalaman ini adalah ketika kita diberi kesempatan untuk mencoba sendiri! Di ruang praktik, di bawah bimbingan para pengajar yang berpengalaman, kita akan diberikan kain putih yang menantang untuk kita hiasi dengan motif-motif yang kita pilih. Dari persiapan kain hingga proses pewarnaan, kita akan merasakan langsung tantangan dan kepuasan yang ada di balik setiap goresan kuas. Selama kita menjelajahi berbagai teknik dan motif, kita juga akan dibimbing untuk memahami makna di balik setiap motif batik. Dari motif yang sederhana hingga yang paling rumit, setiap desain memiliki cerita dan nilai budaya yang terkandung di dalamnya. Ini adalah kesempatan bagi kita untuk belajar lebih dalam tentang keberagaman budaya Indonesia dan mengapresiasi keindahan yang terkandung dalam setiap karya seni.",
        "image1": "https://i.pinimg.com/originals/1a/bc/09/1abc097c8b12d4f97d236ad89060483f.jpg",
        "image2": "https://i.pinimg.com/originals/d1/7a/4c/d17a4c5716c79a637c097d48e19221eb.jpg",
        "image3": "https://i.pinimg.com/originals/fb/1f/96/fb1f96c090d311b95d2a6aa6b7a9ddfd.jpg",
        "image4": "https://i.pinimg.com/originals/6c/8a/72/6c8a72b7b9a1d3b5b203d3582d884dcd.jpg",
    },
    {
        "id": 3,
        "tag": "Latar Cendhani",
        "title": "Pasar Minggu Legi",
        "image1": "https://i.pinimg.com/originals/ed/0c/0f/ed0c0fe96771cd97d8877e4dc63c36a4.jpg",
        "image2": "https://i.pinimg.com/originals/ee/30/e1/ee30e12eb902074a7ebdd9cd63cc728c.jpg",
        "image3": "https://i.pinimg.com/originals/06/22/b6/0622b659262abc9be0dcefc863a08dd0.jpg",
        "image4": "https://i.pinimg.com/originals/0d/f6/1b/0df61b9b09ebbaeefcf7016f1927cd67.jpg",
        "des": "Nama Minggu Legi sendiri merujuk pada penanggalan Jawa, menandakan hari khusus di mana pasar ini berlangsung. Namun, lebih dari sekadar penanggalan, Minggu Legi adalah tempat di mana cerita dan sejarah bertemu, dan aroma jajanan tradisional memenuhi udara. Setiap sudut pasar dipenuhi dengan jajanan tradisional yang menggoda. Dari kue-kue tradisional yang lezat hingga makanan ringan yang unik dan beraneka ragam, semua tersedia di sini. Setiap jajanan memiliki cerita dan keunikan tersendiri, menjadi bagian dari warisan budaya yang harus dijaga dengan baik.",
        "des-Full" : "Nama Minggu Legi sendiri merujuk pada penanggalan Jawa, menandakan hari khusus di mana pasar ini berlangsung. Namun, lebih dari sekadar penanggalan, Minggu Legi adalah tempat di mana cerita dan sejarah bertemu, dan aroma jajanan tradisional memenuhi udara. Setiap sudut pasar dipenuhi dengan jajanan tradisional yang menggoda. Dari kue-kue tradisional yang lezat hingga makanan ringan yang unik dan beraneka ragam, semua tersedia di sini. Setiap jajanan memiliki cerita dan keunikan tersendiri, menjadi bagian dari warisan budaya yang harus dijaga dengan baik. Pasar Minggu Legi bukan hanya tempat untuk berbelanja, tetapi juga merupakan pusat kegiatan sosial dan budaya. Di sini, kita bisa bertemu dengan tetangga, berbincang-bincang dengan pedagang, dan merasakan kehangatan komunitas yang terjalin erat. Meskipun dunia terus berkembang, keberadaan Pasar Minggu Legi tetap menjadi bagian penting dari identitas dan kehidupan masyarakat. Penggunaan keping sebagai alat jual beli menjadi simbol keberlanjutan tradisi dan warisan budaya yang tetap hidup di tengah-tengah perubahan zaman. Dengan mengunjungi Pasar Minggu Legi, kita tidak hanya mendapatkan jajanan tradisional yang lezat, tetapi juga pengalaman yang berharga tentang kehidupan dan budaya lokal. Mari lestarikan pasar tradisional ini dan nikmati keajaiban yang tersimpan di dalamnya.",
    }
]

export default mydata;